### ISSUE TITLE
CSRF token comparison is vulnerable to a timing attack

### ISSUE THREAD

**Issue by tarcieri** [meldium/breach-mitigation-rails#13]
https://github.com/meldium/breach-mitigation-rails/blob/master/lib/breach_mitigation/masking_secrets.rb#L44

The basic setup of BREACH, which requires a MitM, can also be used to measure timing information. Using a non-constant time comparison can also leak the CSRF token.

This should be changed to a constant time comparison

**Comment by bradleybuda** [comment]
Good call - added in f46c0e3dcddad4b79a2090d2f5f453cad7f1ff54 and in version 0.1.0.

**Comment by tarcieri** [comment]
Thanks!
